### PR TITLE
Add language dropdown to generator.

### PR DESCRIPTION
**Pull request by andylolz**
This is a first pass – it’s probably not quite right yet!

Refs #33.

### CODE REVIEW

**Comment by andylolz** [comment]
@blob8108 did you see this one? I’ve applied this and my two other PRs to the version on codeclub.org.uk linked above, so it plays nicely with RTL languages.

**Comment by blob8108** [comment]
What did you do about [the problem you mentioned on #33](https://github.com/blob8108/scratchblocks2/issues/33#issuecomment-67865050)?

**Comment by andylolz** [comment]
Nothing, I’m afraid. If you [try this example](http://scratchblocks.codeclub.org.uk/generator/#project=41036066&lang=hi), you’ll see there are some mistakes. I think the solution relies on modifying the way minification is done.

I realised, though, that we can leave minification mostly as it is, but just tweak it for the cases when there are multiple variables. In fact, we _could_ just tweak it for the cases when there are multiple values that don’t behave as expected – e.g. the Hindi example linked could become: “_2 का _1 मिटा दे”

**Comment by andylolz** [comment]
UPDATE: I’ve roughly fixed the [insert order here](https://github.com/andylolz/scratchblocks2/compare/andylolz:master...33-variable-order). I think that should be a separate pull request, though, since it is another layer of hacky code!

**Pull request closed without merging**
